services:
  jenkins:
    build:
      context: .
      dockerfile: Docker/Dockerfile.jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - .:/workspace
    networks:
      - jenkins-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./test-results:/usr/share/nginx/html/artefacts/test-results
      - ./dist:/usr/share/nginx/html/artefacts/dist
      - ./nginx/index.html:/usr/share/nginx/html/index.html
 
    ports:
      - "80:80"
    networks:
      - jenkins-network

networks:
  jenkins-network:
    driver: bridge
