services:
  jenkins:
    build:
      context: .
      dockerfile: Docker/Dockerfile.jenkins
    ports:
      - "8080:8080"
    environment:
      - JENKINS_EMAIL=humbertogfs55@gmail.com
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - .:/workspace
    networks:
      - jenkins-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: jenkins

  nginx:
    image: nginx:alpine
    volumes:
      - ./test-results:/usr/share/nginx/html/artefacts/test-results
      - ./dist:/usr/share/nginx/html/artefacts/dist
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
    networks:
      - jenkins-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx

  fluentd:
    image: fluent/fluentd:edge-debian
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/fluentd/logs
    networks:
      - jenkins-network


networks:
  jenkins-network:
    driver: bridge
