services:
  jenkins:
    build:
      context: .
      dockerfile: Docker/Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    environment:
      - JENKINS_EMAIL=humbertogfs55@gmail.com
    volumes:
      - ../docker-volumes/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: jenkins

  electron-builder:
    image: electronuserland/builder:wine
    container_name: electron-builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/project
      - ./dist:/project/dist  # Share the build directory (or wherever your source files are located)
    networks:
      - jenkins-network
    environment:
      - DISPLAY=:0  # Set display if you are running Electron in X11 environment
    privileged: true  # Allows the container to run Wine and other tools that may need additional privileges
    command: tail -f /dev/null  # Keeps the container running

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./test-results:/usr/share/nginx/html/artefacts/test-results
      - ./dist:/usr/share/nginx/html/artefacts/dist
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80"
    networks:
      - jenkins-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx

  fluentd:
    image: fluent/fluentd:edge-debian
    container_name: fluentd
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/fluentd/logs
    networks:
      - jenkins-network


networks:
  jenkins-network:
    driver: bridge
