FROM jenkins/jenkins:lts

# Instalar Git, mailutils e outros pacotes necessários
USER root
RUN apt-get update && \
    apt-get install -y git mailutils && \
    apt-get clean

# Voltar para o usuário jenkins
USER jenkins

# Expôr a porta do Jenkins
EXPOSE 8080
